[workspace]
members = ["."]

[package]
name = "rustypus"
version = "0.1.0"
edition = "2021"

[features]
gpu = ["dep:wgpu", "dep:pollster"]

[dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }
rayon = "1.10.0"
serde = { version = "1", features = ["derive"] }
wgpu = { version = "22", optional = true }
pollster = { version = "0.3", optional = true }

[profile.release]
lto = true
codegen-units = 1
